version: 1
services:
  - type: web
    name: book-fair
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: cd backend && node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: book-fair-data
      mountPath: /data
      sizeGB: 1
